-- MySQL Script generated by MySQL Workbench
-- ven. 28 juin 2019 11:50:16 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gameJam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gameJam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gameJam` DEFAULT CHARACTER SET utf8 ;
USE `gameJam` ;

-- -----------------------------------------------------
-- Table `gameJam`.`Building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameJam`.`Building` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `buildingName` VARCHAR(45) NOT NULL,
  `buildingPrice` INT NOT NULL,
  `buildingTime` INT NOT NULL,
  `buildingIncome` INT NOT NULL,
  `buildingIncomeInterval` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameJam`.`UserBase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameJam`.`UserBase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUserBaseBuilding` INT NULL,
  `inhabited` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_UserBase_Building1_idx` (`idUserBaseBuilding` ASC),
  CONSTRAINT `fk_UserBase_Building1`
    FOREIGN KEY (`idUserBaseBuilding`)
    REFERENCES `gameJam`.`Building` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameJam`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameJam`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `UserBase_id` INT NOT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `forgetPassword` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(190) NOT NULL,
  `money` INT NOT NULL,
  `creationBirthday` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_UserBase1_idx` (`UserBase_id` ASC),
  CONSTRAINT `fk_User_UserBase1`
    FOREIGN KEY (`UserBase_id`)
    REFERENCES `gameJam`.`UserBase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameJam`.`Soldat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameJam`.`Soldat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `soldatName` VARCHAR(45) NOT NULL,
  `soldatPrice` INT NOT NULL,
  `soldatDescription` VARCHAR(250) NOT NULL,
  `soldatImage` VARCHAR(250) NOT NULL,
  `soldatAttack` INT NOT NULL,
  `soldatDefense` INT NOT NULL,
  `soldatInitiative` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameJam`.`SoldatUserBase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameJam`.`SoldatUserBase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `UserBase_id` INT NOT NULL,
  `Soldat_id` INT NOT NULL,
  `soldatQuantity` INT NOT NULL,
  INDEX `fk_UserBase_has_Soldat_Soldat1_idx` (`Soldat_id` ASC),
  INDEX `fk_UserBase_has_Soldat_UserBase1_idx` (`UserBase_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_UserBase_has_Soldat_UserBase1`
    FOREIGN KEY (`UserBase_id`)
    REFERENCES `gameJam`.`UserBase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserBase_has_Soldat_Soldat1`
    FOREIGN KEY (`Soldat_id`)
    REFERENCES `gameJam`.`Soldat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
